### ISSUE TITLE
"ERROR in AppModule is not an NgModule webpack: Failed to compile." on first compile but works after edit and recompile.

### ISSUE THREAD

**Issue by chauey** [EladBezalel/material2-start#12]
Hey fellow coders,

I've had this problem for a while with this project. When I run npm start, it errors

ERROR in AppModule is not an NgModule
webpack: Failed to compile.

but if I edit a file and it recompiles, it compiles successsfully. Any ideas? Thanks!

**Comment by chauey** [comment]
https://github.com/angular/angular-cli#updating-angular-cli

i tried to upgrade the angular-cli global and tried again, same problem. 

i tried to upgrade the local angular cli and it worked, success on first compile

so from @angular/cli 1.0.0 to 1.0.6

**Comment by chauey** [comment]
the problem may be related to using yarn instead of npm install.. not sure yet, still looking into it.

**Comment by ThomasBurleson** [comment]
Remove your node_modules dir, `yarn install`, and restart `ng serve`
