### ISSUE TITLE
Responsive Template?

### ISSUE THREAD

**Issue by henriqueweiand** [EladBezalel/material2-start#13]
I'm using this repository as an example to implement a responsive template. I noticed that although this project is using the methods of flex layout the menu of this project does not follow the techniques for such. Has this been taken into account? Look:
![captura de tela 2017-06-02 as 08 26 16](https://cloud.githubusercontent.com/assets/6539492/26723919/32696cc8-476d-11e7-911a-5c4edf50ec37.png)

**Comment by EladBezalel** [comment]
As you might see we're using `<md-sidenav opened>`, to make the opened attribute responsive we need to bind this attribute to flex layout which is currently not available through the html so we need to have in our component as seen [here](https://github.com/angular/flex-layout/wiki/ObservableMedia) hope you'd get it right :)

**Comment by henriqueweiand** [comment]
Thank you @EladBezalel
