### ISSUE TITLE
Remove MaterialModule from the quickstart

### ISSUE THREAD

**Issue by julianobrasil** [EladBezalel/material2-start#15]
The quick starter needs a minor update: the import of material module must be replaced by the individual imports of the used modules.

**Comment by julianobrasil** [comment]
@EladBezalel , I didn't remove the issue at [material 2 repo](https://github.com/angular/material2/issues/4976#issuecomment-306915481) , because I think @DevVersion is using it to track the update of the plunkers used in material 2 oficial docs (at least this is what the change he made in the title meant to me).

Maybe at the end my mistake has turned into something useful  :sunglasses:

**Comment by xuanshenbo** [comment]
Created [pull request](https://github.com/EladBezalel/material2-start/pull/16)
